### ISSUE TITLE
Fails to Run on Windows: 

### ISSUE THREAD

**Issue by krbundy** [nelsopet/Tree_Spectral_Library#7]
When running on the Windows system with a full data cube, using Lecospec Script 5, we received this error after initializing the parallel backend on 7 nodes:
```
Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: Dataset copy failed
```

Should be fixed to allow the system to run predictions with this speclib and classifier.

Also, test whether the lecospec classifier will run as well.

**Comment by nelsopet** [comment]
Tested lecospec PC (not desktop) and it ran successully
